export enum Code {
    OK = 200,
    BAD_REQUEST = 400,
    UNAUTHORIZED_REQUEST = 401,
    NOT_FOUND = 404,
    CREATED = 201,
    INTERNAL_SERVER_ERROR = 500
}

export enum StatusCode {
    OK = "OK",
    BAD_REQUEST = "BAD_REQUEST",
    NOT_FOUND = "NOT_FOUND",
    CREATED = "CREATED",
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
    UNAUTHORIZED_REQUEST = "UNAUTHORIZED_REQUEST"
}